# Interface defintion for dataset

import libraries (not all are used)

In [54]:
import argparse
import numpy as np
from keras.datasets import mnist
from keras.utils import np_utils 
import gzip
from keras.utils.data_utils import get_file
import sys

import cPickle as pickle

import pprint

In [55]:
# assume a patch sze of 3x3 and each item between 0 and 255
# define 2 patches

patch1 = np.empty((3,3), int)
patch2 = np.empty((3,3), int)

In [56]:
patch1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
# write something useful into location 1

patch1[1]=[23,55,254]
print patch1

[[  0   0   0]
 [ 23  55 254]
 [  0   0   0]]


In [58]:
patch2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
# write something useful into location 0, 1, 2

patch2[0] = [0, 33, 77]
patch2[1] = [128, 0, 21]
patch2[2] = [0, 4, 233]

print patch2

[[  0  33  77]
 [128   0  21]
 [  0   4 233]]


In [60]:
# define dataset and append the patches into it
# transform the resulting list into a np array

dataset_list = []

dataset_list.append(patch1)
dataset_list.append(patch2)

dataset = np.array(dataset_list)

In [61]:
# check dataset

dataset

array([[[  0,   0,   0],
        [ 23,  55, 254],
        [  0,   0,   0]],

       [[  0,  33,  77],
        [128,   0,  21],
        [  0,   4, 233]]])

In [63]:
dataset.shape

(2, 3, 3)

In [64]:
# save into pickle format to handover dataset

print 'BEFORE:',
pprint.pprint(dataset)

pickle.dump(dataset, open( "dataset.pkl", "wb" ))



BEFORE:array([[[  0,   0,   0],
        [ 23,  55, 254],
        [  0,   0,   0]],

       [[  0,  33,  77],
        [128,   0,  21],
        [  0,   4, 233]]])



In [48]:
# load again dataset and check 

dataset1 = pickle.load( open( "dataset.pkl", "rb" ) )
print 'AFTER:',
pprint.pprint(dataset1)


print 'EQUAL?:', (dataset == dataset1)

AFTER:array([[[ 23,  55, 254],
        [ 23,  55, 254],
        [ 21,   4, 233]],

       [[  0,  33,  77],
        [128,   0,  21],
        [  0,   4, 233]]])
 EQUAL?: [[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


### same for labels


In [49]:
label1 = 3
label2 = 8

In [50]:
labels = []

In [51]:
labels.append(label1)
labels.append(label2)

print labels

[3, 8]


In [52]:
pickle.dump(labels, open( "labels.pkl", "wb" ))