In [1]:
import os
import numpy as np
import shutil
import scipy.misc
import cPickle as pickle
from matplotlib import pyplot as plt
from PIL import Image, ImageFont, ImageDraw

/Users/peterhirt/anaconda/envs/theano/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [2]:
#font file imported in top directory
font = ImageFont.truetype( '../fonts/arial.ttf', 20)

In [3]:
errorfile = open('../errorfile.txt', 'w')
#errorfile.close()

In [4]:
# customisation part

# define the dicom image format bmp or jpg
typei='bmp'

# dicom file size in pixels
dimtabx = 512
dimtaby = 512

# patch size in pixels
dimpavx =32
dimpavy = 32

# threshold for probability
thr = 0.8

In [5]:
#pickle with predicted classes
precclaf='../pickle/predicted_classes.pkl'
 #pickle with predicted probabilities
precprobf='../pickle/predicted_probabilities.pkl'

In [6]:
precclaf

'../pickle/predicted_classes.pkl'

In [7]:
one_folder_up = os.path.dirname(os.getcwd())
print one_folder_up

/Users/peterhirt/datascience/ild-cnn


In [9]:
dirpatientdb = os.path.join(one_folder_up,'predict')
print dirpatientdb

/Users/peterhirt/datascience/ild-cnn/predict


In [44]:
#directory name with predict out dabasase, will be created in current directory
dirpatientoutdb = os.path.join(one_folder_up,'predict_out')
print dirpatientoutdb

/Users/peterhirt/datascience/ild-cnn/predict_out


In [11]:
# subdirectory name to put images
imgdirname = 'jpeg'

In [13]:
# subdirectory name to colect pkl files resulting from prediction
predoutdirname = 'pickle'

In [14]:
# color of labels

red=(255,0,0)
green=(0,255,0)
blue=(0,0,255)
yellow=(255,255,0)
cyan=(0,255,255)
purple=(255,0,255)
white=(255,255,255)

In [16]:
classif = {
    'consolidation': 0,
     'fibrosis': 1,
     'ground_glass': 2,
     'healthy': 3,
     'micronodules': 4,
     'reticulation': 5
    }
classifc = {
    'consolidation': red,
    'fibrosis': blue,
     'ground_glass': yellow,
     'healthy': green,
     'micronodules': cyan,
    'reticulation': purple
    }

In [18]:
def fidclass(numero):
    """return class from number"""
    found=False
    for cle, valeur in classif.items():
        
        if valeur == numero:
            found=True
            return cle
      
    if not found:
        return 'unknown'

In [19]:
def interv(borne_inf, borne_sup):
    """Générateur parcourant la série des entiers entre borne_inf et borne_sup.
    inclus
    Note: borne_inf doit être inférieure à borne_sup"""
    
    while borne_inf <= borne_sup:
        yield borne_inf
        borne_inf += 1

In [20]:
def tagview(fig,text,pro,x,y):
    """write text in image according to label and color"""
    imgn=Image.open(fig)
    draw = ImageDraw.Draw(imgn)
    col=classifc[text]

    deltay=25*(classif[text]%3)
    deltax=175*(classif[text]//3)
    #print text, col
    draw.text((x+deltax, y+deltay),text+' '+pro,col,font=font)
    imgn.save(fig)

In [21]:
def tagviews(fig,text,x,y):
    """write simple text in image """
    imgn=Image.open(fig)
    draw = ImageDraw.Draw(imgn)
    draw.text((x, y),text,white,font=font)
    imgn.save(fig)

In [22]:
def maxproba(proba):
    """looks for max probability in result"""
    lenp = len(proba)
    m=0
    for i in interv(0,lenp-1):
        if proba[i]>m:
            m=proba[i]
    return m

In [46]:
def remove_folder(path):
    # check if folder exists
    if os.path.exists(path):
         # remove if exists
         shutil.rmtree(path)
         print('this direc exist:',path)

In [24]:
def loadpkl(f,do):
    # create image directory and load pkl files
    dop =os.path.join(do,predoutdirname)
    # pickle with predicted classes
    preclasspick= os.path.join(dop,precclaf)
    # pickle with predicted probabilities
    preprobpick= os.path.join(dop,precprobf)
    # generate input tables from pickles
    dd = open(preclasspick,'rb')
    my_depickler = pickle.Unpickler(dd)
    preclass = my_depickler.load()
#    preclass[0]=0
#    preclass[1]=1
#    preclass[2]=2
#    preclass[3]=3
#    preclass[4]=4
#    preclass[5]=5
    dd.close()
    dd = open(preprobpick,'rb')
    my_depickler = pickle.Unpickler(dd)
    preprob = my_depickler.load()
    dd.close()  
    return (preclass,preprob)

In [39]:
listpatient=os.listdir(dirpatientdb)    
listpatient.pop(0)
listpatient121 = []
listpatient121.append(listpatient[1])
print listpatient121

['121']


# actual code

In [42]:
print len(listpatient121)
print listpatient121

1
['121']


In [47]:
for f in listpatient121:
    print('work on: ',f)
    do = os.path.join(dirpatientoutdb,f)
    print do
    doj = os.path.join(do,imgdirname)
    print doj
    remove_folder(doj)
    os.mkdir(doj)
    (preclass,preprob)=loadpkl(f,do)

('work on: ', '121')
/Users/peterhirt/datascience/ild-cnn/predict_out/121
/Users/peterhirt/datascience/ild-cnn/predict_out/121/jpeg


OSError: [Errno 2] No such file or directory: '/Users/peterhirt/datascience/ild-cnn/predict_out/121/jpeg'

In [ ]:
    doj = os.path.join(do,imgdirname)
    remove_folder(doj)
    os.mkdir(doj)
    (preclass,preprob)=loadpkl(f,do)

In [48]:
from six.moves import cPickle
import cPickle as pickle

In [51]:
predicted_classes = pickle.load( open( "../pickle/predicted_classes.pkl", "rb" ) )
predicted_probabilities = pickle.load( open( "../pickle/predicted_probabilities.pkl", "rb" ) )
X_file_reference = pickle.load( open( "../pickle/X_file_reference.pkl", "rb" ) )

In [50]:
predicted_classes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 2, 3, 1, 3, 2, 2, 2, 2, 1, 1, 1, 1, 3, 1, 1, 1, 1,
       1, 2, 2, 1, 3, 2, 2, 1, 2, 2, 1, 3, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 2,
       2, 1, 2, 1, 3, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 3, 2, 3, 1, 3, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1,
       1, 1,

In [52]:
predicted_probabilities

array([[  1.33350966e-08,   9.99103427e-01,   8.96522717e-04,
          1.03297024e-10,   1.22284682e-10,   5.38606031e-08],
       [  8.85062400e-06,   9.55910444e-01,   1.13144813e-06,
          4.40795682e-02,   6.30839114e-09,   2.76626690e-11],
       [  2.00469316e-07,   9.69777763e-01,   3.01982090e-02,
          7.64456054e-10,   2.62022922e-07,   2.35684511e-05],
       ..., 
       [  3.52787916e-12,   9.99415517e-01,   5.84509806e-04,
          8.00624690e-15,   1.83748719e-12,   7.32938016e-11],
       [  2.43843580e-16,   9.99999940e-01,   8.10801595e-08,
          5.94657661e-19,   1.98992775e-16,   2.57097186e-12],
       [  1.71554027e-09,   9.99838591e-01,   1.61364602e-04,
          4.26771174e-10,   7.51560147e-09,   6.04835364e-08]])

In [54]:
X_file_reference[0:5]

array(['p_0001_160_256.bmp', 'p_0002_128_256.bmp', 'p_0002_128_288.bmp',
       'p_0002_160_256.bmp', 'p_0002_160_288.bmp'], 
      dtype='|S18')

In [56]:
print predicted_classes.shape
print predicted_probabilities.shape
print X_file_reference.shape

(338,)
(338, 6)
(338,)


In [60]:
results = np.concatenate((predicted_classes, X_file_reference))

In [61]:
results[0:5]

array(['1', '1', '1', '1', '1'], 
      dtype='|S21')

In [62]:
a = [[1],[2],[3]]

In [64]:
b = [[4],[5],[6]]

In [66]:
np.concatenate((a,b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
aa = [1,2,3]
bb = [4,5,6]

In [71]:
np.concatenate((aa.T,bb.T), axis=1)

AttributeError: 'list' object has no attribute 'T'

In [83]:
aaa = predicted_classes[0:3]
bbb = X_file_reference[0:3]
X = [200,210,220]
Y = [100,150,200]

In [78]:
print aaa[0]

1


In [84]:
c = np.zeros((3, 3))
for i in range(3):
    c[i][0] = aaa[i]
    c[i][1] = X[i]
    c[i][2] = Y[i]

In [85]:
c

array([[   1.,  200.,  100.],
       [   1.,  210.,  150.],
       [   1.,  220.,  200.]])

In [86]:
bbb[0].count('_')

3

In [91]:
bbb[0].split('_')

['p', '0001', '160', '256.bmp']

In [96]:
bbbb = bbb[0].split('.')


['p_0001_160_256', 'bmp']

In [97]:
print bbbb[0]

p_0001_160_256


In [98]:
print bbbb[0].split('_')

['p', '0001', '160', '256']
